linters:
  enable-all: true
  disable:
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - structcheck
    - scopelint
    - varcheck
